package com.bhardwaj.pokemon.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 8.dp

val PAGING_INDICATOR_WIDTH = 12.dp
val PAGING_INDICATOR_SPACING = 8.dp

val TOP_BAR_HEIGHT = 56.dp
val HERO_ITEM_HEIGHT = 400.dp
val SHIMMER_NAME_PLACEHOLDER_HEIGHT = 30.dp
val SHIMMER_ABOUT_PLACEHOLDER_HEIGHT = 15.dp
val SHIMMER_RATING_PLACEHOLDER_HEIGHT = 20.dp
val NETWORK_ERROR_ICON_SIZE = 120.dp
val INFO_ICON_SIZE = 32.dp
val DETAILS_LOGO_ICON_SIZE = 32.dp
val DETAILS_CLOSE_ICON_SIZE = 32.dp

val BOTTOM_SHEET_MINIMUM_HEIGHT = 140.dp
val BOTTOM_SHEET_EXPANDED_RADIUS = 0.dp
val BOTTOM_SHEET_COLLAPSED_RADIUS = 40.dp